Universe = vanilla
job = ffZee
cmd = mymain00
args=$(cluster).$(process)
output = submissionTest/$(job)_$(cluster).$(process).out
error = submissionTest/$(job)_$(cluster).$(process).err
log = submissionTest/$(job)_$(cluster).$(process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
input	=	mymain00.cmnd
transfer_input_files	=	mymain00.cmnd


request_cpus = 1
request_memory=1
request_disk=100000

queue 1
